server:
  port: 8081

spring:
  application:
    name: accounts
    
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgresql-arquitecturaut.alwaysdata.net:5432/arquitecturaut_bdd_accounts}
    username: ${SPRING_DATASOURCE_USERNAME:arquitecturaut_us}
    password: ${SPRING_DATASOURCE_PASSWORD:Caramelo200}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    properties:
      hibernate:
        format_sql: true
        
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: America/Guayaquil

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    
logging:
  level:
    com.pichincha: INFO
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR